# site settings
title: home
subtitle: kāinga
#https://formspree.io/f/mjglnepa
#email: youremailaddress@gmail.com
description: Bring your dreams
baseurl: "/karamu"
url: "https://omegasemantic.github.io"
author:
street_address: Wainui Road
city: Whaingaroa
country: Aotearoa

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6


# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- vendor/
